'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'one.js'),'utf8');
const db=new Map();
const storage={getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,String(v)),removeItem:k=>db.delete(k)};
const sandbox={localStorage:storage};
vm.runInNewContext(source,sandbox,{filename:'one.js'});
const one=sandbox.ONEEngine;
assert.ok(one,'ONE engine unavailable');
assert.equal(one.ATOZ.length,26);
assert.equal(one.DIVISIONS.length,9);
assert.equal(one.PROVIDERS.length,19);
assert.equal(one.PROVIDERS.some(p=>p.support==='connected'),false,'Providers are mislabeled connected');
assert.equal(one.resolveIntent('add task buy groceries').kind,'task');
assert.equal(one.resolveIntent('note remember keys').kind,'note');
assert.equal(one.resolveIntent('pay rent').kind,'unsupported');
assert.equal(one.resolveIntent('transfer $50').kind,'unsupported');
assert.equal(one.grantProvider('gmail','read').ok,false);
assert.equal(one.grantProvider('healthkit','action').ok,false);
assert.equal(one.executeIntent({kind:'open',value:'gmail'}).ok,false);
let r=one.executeIntent(one.resolveIntent('add task buy groceries'));
assert.equal(r.ok,true);
assert.equal(one.state.tasks.length,1);
r=one.executeIntent(one.resolveIntent('note remember keys'));
assert.equal(r.ok,true);
assert.equal(one.state.notes.length,1);
r=one.addEvent('Meeting','2026-10-20');assert.equal(r.ok,true);
assert.equal(one.runFlow('work').ok,true);
assert.equal(one.state.activeDomain,'T');
r=one.executeIntent(one.resolveIntent('open TABOR 1-2-3 FACTORY'));
assert.equal(r.open,'../index.html');
r=one.executeIntent(one.resolveIntent('zero mode'));
assert.equal(r.ok,true);
assert.equal(one.state.zero,true);
r=one.executeIntent(one.resolveIntent('add task blocked'));
assert.equal(r.ok,false);
assert.equal(one.state.tasks.length,1);
one.executeIntent(one.resolveIntent('zero off'));
assert.equal(one.state.zero,false);
const exported=JSON.parse(one.exportData());
assert.equal(exported.schema,'tabor123.one.v1');
assert.equal(exported.tasks.length,1);
one.clearData();
assert.equal(one.state.tasks.length,0);
console.log('PASS ONE The Last App: 24 local engine/permission assertions.');
