'use strict';
/* TABOR 1-2-3 FACTORY™ — Local-first archive and media manager.
   No network uploads, account tokens, trackers, or public repository writes.
   All imported bytes stay in browser IndexedDB until the user exports them or clears site data. */
const DB_NAME='tabor123_vault_v1', DB_VERSION=1, PROJECTS_KEY='tabor123_projects_v1';
const $=id=>document.getElementById(id);
const state={db:null,records:[],mode:'assets',limit:30,urls:[],busy:false,selection:[],projectCount:0};
const assetExtensions={'.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.gif':'image/gif','.svg':'image/svg+xml','.avif':'image/avif','.heic':'image/heic','.mp4':'video/mp4','.mov':'video/quicktime','.webm':'video/webm','.mp3':'audio/mpeg','.wav':'audio/wav','.m4a':'audio/mp4','.pdf':'application/pdf','.html':'text/html','.htm':'text/html','.md':'text/markdown','.txt':'text/plain','.py':'text/x-python','.json':'application/json','.js':'text/javascript','.css':'text/css','.csv':'text/csv','.zip':'application/zip','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation','.epub':'application/epub+zip','.stl':'model/stl','.glb':'model/gltf-binary','.gltf':'model/gltf+json'};
function guessType(name,type){if(type&&type!=='application/octet-stream')return type;const ext=name.toLowerCase().match(/\.[a-z0-9]+$/)?.[0];return assetExtensions[ext]||'application/octet-stream'}
function extGroup(m){if(m.startsWith('image/'))return 'image';if(m.startsWith('video/'))return 'video';if(m.startsWith('audio/'))return 'audio';if(m.includes('pdf')||m.includes('word')||m.includes('text')||m.includes('json')||m.includes('csv')||m.includes('html')||m.includes('zip'))return 'document';return 'file'}
const fmt=n=>n>=1073741824?(n/1073741824).toFixed(1)+' GB':n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' bytes';
function inform(message){$('progress').textContent=message}
function safeName(x){return String(x||'Untitled').replace(/[\u0000-\u001f]/g,' ').slice(0,220)}
function newId(){return (typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function')?crypto.randomUUID():'v'+Date.now()+'_'+Math.random().toString(36).slice(2)}
function reqResult(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Database error'))})}
function txnDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||Error('Storage write failed'));tx.onabort=()=>reject(tx.error||Error('Storage write aborted'))})}
function openVault(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window)){reject(Error('This browser does not support private file storage'));return}const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('records')){const s=db.createObjectStore('records',{keyPath:'id'});s.createIndex('fingerprint','fingerprint',{unique:true});s.createIndex('kind','kind')}if(!db.objectStoreNames.contains('blobs'))db.createObjectStore('blobs',{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error('Could not open private storage'));request.onblocked=()=>reject(Error('Close other Factory tabs and retry.'))})}
async function loadRecords(){state.records=await reqResult(state.db.transaction('records','readonly').objectStore('records').getAll());state.records.sort((a,b)=>String(b.importedAt).localeCompare(String(a.importedAt)));const filter=$('projectFilter');if(filter){const prior=filter.value;filter.replaceChildren();const any=textNode('option','Every collection');any.value='';filter.append(any);[...new Set(state.records.map(x=>x.project||'Unsorted'))].sort().forEach(name=>{const opt=textNode('option',name);opt.value=name;filter.append(opt)});filter.value=[...filter.options].some(x=>x.value===prior)?prior:'';}let projects=[];try{projects=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]')}catch(e){}if(!Array.isArray(projects))projects=[];state.projectCount=projects.length;$('statAssets').textContent=state.records.filter(x=>x.kind==='asset').length;$('statChats').textContent=state.records.filter(x=>x.kind==='conversation').length;$('statProjects').textContent=state.projectCount;render()}
async function hasFingerprint(fp){return reqResult(state.db.transaction('records','readonly').objectStore('records').index('fingerprint').getKey(fp))}
async function digest(buffer){if(buffer.byteLength<=55000000&&crypto.subtle){const hash=await crypto.subtle.digest('SHA-256',buffer);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')}return null}
async function saveRecord(record,blob){const existed=await hasFingerprint(record.fingerprint);if(existed)return false;const tx=state.db.transaction(blob?['records','blobs']:['records'],'readwrite');tx.objectStore('records').add(record);if(blob)tx.objectStore('blobs').add({id:record.id,blob});await txnDone(tx);return true}
async function importAsset(name,bytes,type,origin,project='Unsorted'){const mime=guessType(name,type);const buffer=bytes instanceof ArrayBuffer?bytes:await bytes.arrayBuffer();const sha=await digest(buffer);const fingerprint=sha?'sha256:'+sha:'name-size:'+name+'|'+buffer.byteLength+'|'+origin;const blob=new Blob([buffer],{type:mime});const entry={id:newId(),kind:'asset',name:safeName(name),mime,group:extGroup(mime),size:buffer.byteLength,origin:origin||'user import',importedAt:new Date().toISOString(),fingerprint,sha256:sha,project,tags:[],summary:'',sourceFilename:safeName(name)};return saveRecord(entry,blob)}
function extractChatText(conv){const arr=[];const mapping=conv.mapping||{};for(const node of Object.values(mapping)){const m=node?.message;if(!m||!m.content)continue;const role=String(m.author?.role||'unknown');if(!['user','assistant','system','developer'].includes(role))continue;const parts=Array.isArray(m.content.parts)?m.content.parts:[];let content=parts.map(p=>typeof p==='string'?p:(p&&typeof p.text==='string'?p.text:'')).filter(Boolean).join('\n');if(!content&&typeof m.content.text==='string')content=m.content.text;if(!content.trim())continue;arr.push({at:Number(m.create_time||node.create_time||0),role,text:content})}arr.sort((a,b)=>a.at-b.at);return arr.map(m=>m.role.toUpperCase()+': '+m.text).join('\n\n')}
async function importConversation(conv,origin){if(!conv||typeof conv!=='object')return false;const title=safeName(conv.title||'Untitled chat');let content=extractChatText(conv);if(!content&&Array.isArray(conv.messages))content=conv.messages.map(m=>String(m.role||'MESSAGE')+': '+String(m.content||'')).join('\n\n');if(!content)return false;const origId=String(conv.id||conv.conversation_id||'');const chatBuffer=new TextEncoder().encode(content).buffer;const chatDigest=await digest(chatBuffer);const fingerprint='conversation:'+ (origId||title)+':'+(chatDigest||String(content.length)+'|'+content.slice(-100));const r={id:newId(),kind:'conversation',name:title,mime:'text/plain',group:'conversation',size:new TextEncoder().encode(content).byteLength,origin,importedAt:new Date().toISOString(),fingerprint,project:'Unsorted',tags:[],summary:content.slice(0,300),text:content,sourceFilename:'conversations.json'};return saveRecord(r)}
function getUint16(view,offset){return view.getUint16(offset,true)}function getUint32(view,offset){return view.getUint32(offset,true)}
function listZipFiles(buffer){const view=new DataView(buffer);let eocd=-1;for(let i=buffer.byteLength-22;i>=Math.max(0,buffer.byteLength-65557);i--){if(getUint32(view,i)===0x06054b50){eocd=i;break}}if(eocd<0)throw Error('ZIP central directory not found');const count=getUint16(view,eocd+10),offset=getUint32(view,eocd+16);if(count===65535||offset===0xffffffff)throw Error('ZIP64 archive not supported on this iPhone importer. Extract a smaller archive in Files.');const decoder=new TextDecoder();const entries=[];let cursor=offset;for(let i=0;i<count;i++){if(cursor+46>buffer.byteLength||getUint32(view,cursor)!==0x02014b50)throw Error('Invalid ZIP index');const method=getUint16(view,cursor+10),compSize=getUint32(view,cursor+20),plainSize=getUint32(view,cursor+24),nameLen=getUint16(view,cursor+28),extraLen=getUint16(view,cursor+30),commentLen=getUint16(view,cursor+32),localOffset=getUint32(view,cursor+42);const name=decoder.decode(new Uint8Array(buffer,cursor+46,nameLen));entries.push({name,method,compSize,plainSize,localOffset});cursor+=46+nameLen+extraLen+commentLen}return entries}
async function zipBytes(archive,entry){if(entry.plainSize>75000000||entry.compSize>150000000)throw Error('Entry exceeds mobile import safety limit');const view=new DataView(archive);const pos=entry.localOffset;if(pos+30>archive.byteLength||getUint32(view,pos)!==0x04034b50)throw Error('Invalid ZIP entry');const dataStart=pos+30+getUint16(view,pos+26)+getUint16(view,pos+28);if(dataStart+entry.compSize>archive.byteLength)throw Error('ZIP entry outside archive');const bytes=new Uint8Array(archive,dataStart,entry.compSize);if(entry.method===0)return bytes.slice().buffer;if(entry.method!==8)throw Error('Unsupported ZIP compression method '+entry.method);if(!('DecompressionStream'in window))throw Error('Your browser cannot unzip compressed archives. Extract them first using the Files app.');let stream;try{stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));const result=await new Response(stream).arrayBuffer();if(result.byteLength>75000000)throw Error('Decompressed entry too large');return result}catch(e){throw Error('Cannot unpack Deflate ZIP on this browser. Extract with Files, then import its contents. '+e.message)}}
function eligibleFile(name){if(name.endsWith('/'))return false;if(name.startsWith('__MACOSX/')||name.includes('/.DS_Store')||name.endsWith('.DS_Store'))return false;if(/(^|\/)\./.test(name)&&!name.endsWith('.md'))return false;return true}
async function importZip(file){if(file.size>200000000)throw Error('ZIP larger than 200MB. Split it or extract smaller groups in iPhone Files.');const archive=await file.arrayBuffer(),entries=listZipFiles(archive);let added=0,duplicate=0,skipped=0,chats=0;let assetProjects={};const manifestEntry=entries.find(x=>x.name.split('/').pop()==='factory-manifest.json');if(manifestEntry){try{const raw=await zipBytes(archive,manifestEntry);const manifest=JSON.parse(new TextDecoder().decode(raw));if(manifest.schema==='tabor123.asset-pack.v1'&&Array.isArray(manifest.assets)){for(const asset of manifest.assets){if(asset&&typeof asset.filename==='string'&&typeof asset.project==='string')assetProjects[asset.path||asset.filename]=asset.project.slice(0,100)}}}catch(e){}}for(let i=0;i<entries.length;i++){const e=entries[i];if(!eligibleFile(e.name))continue;const label=e.name.split('/').pop();if(!label)continue;inform('Importing '+(i+1)+'/'+entries.length+': '+label);if(e.plainSize>75000000){skipped++;continue}let content;try{content=await zipBytes(archive,e)}catch(err){skipped++;inform('Skipped '+label+': '+err.message);continue}if(label.toLowerCase()==='conversations.json'){try{const parsed=JSON.parse(new TextDecoder().decode(content));const list=Array.isArray(parsed)?parsed:(Array.isArray(parsed.conversations)?parsed.conversations:[]);for(const conv of list){if(await importConversation(conv,'ChatGPT export: '+file.name)){chats++}}}catch(err){skipped++;inform('Could not parse ChatGPT conversations.json: '+err.message)}continue}
if(label==='factory-manifest.json'){try{const manifest=JSON.parse(new TextDecoder().decode(content));if(manifest.schema==='tabor123.asset-pack.v1')inform('Recognized Factory asset pack: '+file.name)}catch(err){}continue}
const t=guessType(label);try{if(await importAsset(label,content,t,'ZIP: '+file.name,assetProjects[e.name]||assetProjects[label]||'Unsorted')){added++}else duplicate++}catch(err){skipped++}}
return {added,duplicate,skipped,chats}}
async function importJsonFile(file){const content=await file.text();if(content.length>95000000)throw Error('JSON file too large for mobile parser');const value=JSON.parse(content);const list=Array.isArray(value)?value:Array.isArray(value.conversations)?value.conversations:null;if(list&&list.some(v=>v&&typeof v==='object'&&v.mapping)){let chats=0;for(const conv of list){if(await importConversation(conv,file.name))chats++}return {chats,added:0,duplicate:0,skipped:0}}if(value.schema==='tabor123.asset-pack.v1')return {chats:0,added:await importAsset(file.name,await file.arrayBuffer(),file.type,'JSON index')?1:0,duplicate:0,skipped:0};return {chats:0,added:await importAsset(file.name,await file.arrayBuffer(),file.type,'JSON file')?1:0,duplicate:0,skipped:0}}
async function doImport(){if(state.busy)return;const files=[...$('importFiles').files];if(!files.length){inform('Select one or more files first.');return}state.busy=true;$('startImport').disabled=true;let totals={added:0,chats:0,duplicate:0,skipped:0};try{for(const f of files){inform('Reading '+f.name+' ('+fmt(f.size)+')…');let result;if(f.name.toLowerCase().endsWith('.zip'))result=await importZip(f);else if(f.name.toLowerCase()==='conversations.json')result=await importJsonFile(f);else result={added:await importAsset(f.name,await f.arrayBuffer(),f.type,'iPhone Files import')?1:0,chats:0,duplicate:0,skipped:0};for(const k of Object.keys(totals))totals[k]+=result[k]||0}inform('Imported '+totals.added+' original files and '+totals.chats+' conversations. '+totals.duplicate+' duplicates skipped; '+totals.skipped+' files not imported.');await loadRecords();$('importFiles').value=''}catch(err){inform('Import paused: '+err.message+'. Already imported files are saved.');await loadRecords()}finally{state.busy=false;$('startImport').disabled=false}}
function getById(id){return state.records.find(x=>x.id===id)}
async function getBlob(id){const v=await reqResult(state.db.transaction('blobs','readonly').objectStore('blobs').get(id));return v?.blob}
function clearObjectUrls(){state.urls.forEach(url=>URL.revokeObjectURL(url));state.urls=[]}
function textNode(tag,value){const el=document.createElement(tag);el.textContent=String(value??'');return el}
function actionButton(title,cb){const b=textNode('button',title);b.type='button';b.onclick=cb;return b}
function safeFilename(name){return name.replace(/[\\/:*?"<>|]/g,'_')}
async function downloadOriginal(id){const r=getById(id);if(!r)return;const data=r.kind==='conversation'?new Blob([r.text],{type:'text/plain'}):await getBlob(id);if(!data){inform('Original file not available');return}const url=URL.createObjectURL(data);const link=document.createElement('a');link.href=url;link.download=safeFilename(r.kind==='conversation'?r.name+'.txt':r.name);link.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function editTags(id){const r=getById(id);if(!r)return;const response=prompt('Comma-separated tags for this file:',(r.tags||[]).join(', '));if(response===null)return;const tags=response.split(',').map(x=>x.trim().slice(0,60)).filter(Boolean).slice(0,25);const tx=state.db.transaction('records','readwrite');tx.objectStore('records').put({...r,tags});await txnDone(tx);await loadRecords();inform('Tags updated for '+r.name+'.')}
async function deleteAsset(id){const r=getById(id);if(!r||!confirm('Permanently delete this local Vault copy of '+r.name+'? Keep a backup of the original first.'))return;const tx=state.db.transaction(['records','blobs'],'readwrite');tx.objectStore('records').delete(id);tx.objectStore('blobs').delete(id);await txnDone(tx);await loadRecords();inform('Removed local copy of '+r.name+'.')}
async function linkProject(id){const r=getById(id);if(!r)return;const target=prompt('Project or collection name for this item:',r.project==='Unsorted'?'':r.project);if(target===null)return;const project=safeName(target.trim());if(!project){inform('Project name is required.');return}const tx=state.db.transaction('records','readwrite');tx.objectStore('records').put({...r,project});await txnDone(tx);await loadRecords();inform('Linked '+r.name+' to '+project+'. Original stored once.')};
async function saveToProjects(id){const r=getById(id);if(!r)return;let projects=[];try{projects=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]')}catch(e){}if(!Array.isArray(projects))projects=[];const title=r.name;projects.unshift({id:newId(),name:title,type:r.kind==='conversation'?'ChatGPT conversation':'Imported '+r.group,description:(r.kind==='conversation'?r.text.slice(0,16000):'Original Vault asset: '+r.name+' | Vault reference ID: '+r.id+'. Find it under Archive & Media Vault on this device.'),status:'Idea',created:new Date().toISOString(),vaultAssetId:r.id});try{localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects));inform('Factory project created. This project references the original locally.')}catch(e){inform('Browser storage is full; could not save project.')}await loadRecords()};
async function showAsset(id,card){const r=getById(id);if(!r)return;const existing=card.querySelector('.preview-slot');if(existing){existing.remove();return}const body=document.createElement('div');body.className='preview-slot';body.style.marginTop='12px';if(r.kind==='conversation'){const area=textNode('div',r.text.slice(0,45000));area.className='preview';body.append(area)}else{const blob=await getBlob(id);if(!blob){body.append(textNode('p','Original bytes not found.'));card.append(body);return}if(r.group==='image'&&!r.mime.includes('svg')){const img=document.createElement('img');const url=URL.createObjectURL(blob);state.urls.push(url);img.src=url;img.alt=r.name;img.loading='lazy';body.append(img)}else if(r.group==='video'){const video=document.createElement('video');const url=URL.createObjectURL(blob);state.urls.push(url);video.src=url;video.controls=true;video.preload='metadata';body.append(video)}else if(r.group==='audio'){const aud=document.createElement('audio');const url=URL.createObjectURL(blob);state.urls.push(url);aud.src=url;aud.controls=true;body.append(aud)}else if(r.mime.startsWith('text/')||r.mime==='application/json'||r.name.endsWith('.py')){const text=await blob.slice(0,50000).text();const box=textNode('div',text);box.className='preview';body.append(box)}else body.append(textNode('p','Preview not supported for this file type. Use Download original.'))}card.append(body)}
function normalizedSearch(r){return [r.name,r.group,r.project,r.kind,r.origin,r.summary,...(r.tags||[])].join(' ').toLowerCase()}
function collectionCards(records,root){const groups=new Map();for(const r of records){const key=r.project||'Unsorted';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)}for(const [name,items]of groups){const card=document.createElement('div');card.className='tile';card.append(textNode('h3',name),textNode('p',items.length+' originals/conversations'));card.append(actionButton('See collection',()=>{$('search').value=name;state.mode='assets';render()}));root.append(card)}}
function render(){clearObjectUrls();const q=$('search').value.toLowerCase().trim();let found=state.records.filter(r=>!q||normalizedSearch(r).includes(q)||((r.kind==='conversation')&&r.text.toLowerCase().includes(q)));const category=$('mediaType')?.value||'',collection=$('projectFilter')?.value||'';found=found.filter(r=>(!category||r.group===category)&&(!collection||(r.project||'Unsorted')===collection));let scoped=state.mode==='assets'?found.filter(r=>r.kind==='asset'):state.mode==='chats'?found.filter(r=>r.kind==='conversation'):found;$('resultsCount').textContent=scoped.length+' matching '+(state.mode==='assets'?'files':state.mode==='chats'?'conversations':'records')+'. No server upload.';const root=$('results');root.replaceChildren();if(state.mode==='collections'){collectionCards(scoped,root);$('showMore').hidden=true;return}for(const r of scoped.slice(0,state.limit)){const card=document.createElement('div');card.className='tile';const heading=textNode('h3',r.name);heading.style.overflowWrap='anywhere';card.append(heading);card.append(textNode('small',(r.kind==='conversation'?'ChatGPT conversation':r.group)+' · '+fmt(r.size||0)+' · '+(r.project||'Unsorted')));if(r.kind==='conversation'){const preview=textNode('p',r.summary||'');preview.style.maxHeight='5rem';preview.style.overflow='hidden';card.append(preview)}else{if(r.group==='image'&&r.mime!=='image/svg+xml'){const thumb=document.createElement('img');thumb.alt=r.name;thumb.loading='lazy';thumb.style.marginTop='12px';card.append(thumb);getBlob(r.id).then(blob=>{if(!blob||!thumb.isConnected)return;const url=URL.createObjectURL(blob);state.urls.push(url);thumb.src=url}).catch(()=>{})}else card.append(textNode('p',r.origin))}const controls=document.createElement('div');controls.className='row';controls.style.marginTop='12px';controls.append(actionButton('Preview',()=>showAsset(r.id,card)),actionButton('Download',()=>downloadOriginal(r.id)),actionButton('Link to project',()=>linkProject(r.id)),actionButton('Edit tags',()=>editTags(r.id)),actionButton('Make Factory project',()=>saveToProjects(r.id)),actionButton('Delete local',()=>deleteAsset(r.id)));card.append(controls);root.append(card)}$('showMore').hidden=scoped.length<=state.limit;if(!scoped.length)root.textContent='No matches yet. Import a ChatGPT export, Factory asset pack or files from your device.'}
function mode(name){state.mode=name;state.limit=30;render()}
async function exportIndex(){const manifest={schema:'tabor123.vault-index.v1',created:new Date().toISOString(),warning:'Index only. Does not contain image/video/source file bytes.',records:state.records.map(({text,...rest})=>({...rest,conversationExcerpt:rest.kind==='conversation'?text?.slice(0,500):undefined}))};const b=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'});const url=URL.createObjectURL(b);const a=document.createElement('a');a.href=url;a.download='tabor-vault-index.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function init(){try{state.db=await openVault();await loadRecords();inform('Ready. Your archive remains stored on this device unless you export it.');}catch(err){inform('Private Vault is unavailable: '+err.message);$('startImport').disabled=true;return}
$('startImport').onclick=doImport;$('showHow').onclick=()=>{$('how').hidden=!$('how').hidden};$('showAssets').onclick=()=>mode('assets');$('showChats').onclick=()=>mode('chats');$('showCollections').onclick=()=>mode('collections');$('refreshVault').onclick=loadRecords;$('search').oninput=()=>{state.limit=30;render()};$('mediaType').onchange=()=>{state.limit=30;render()};$('projectFilter').onchange=()=>{state.limit=30;render()};$('showMore').onclick=()=>{state.limit+=30;render()};$('exportIndex').onclick=exportIndex}
document.addEventListener('DOMContentLoaded',init);